---
format: 
  html:
    output-file: About.html
    minimal: true
engine: knitr
brand: false
---

# About this Website

This website holds the NBS Water Quality Monitoring and Restoration Program's results. Within this page, you can explore our site maps, generate graphs to compare sample sites or tests, print entire data sets, and more!

## About the NBS Water Quality Monitoring and Restoration Program

The water quality program began testing in February of 2026 and monitors the chemical, biological, and physical characteristics of Norman Bird Sanctuary's aquatic systems. The list of everything we test along with the field and lab equipment we use can be found on the water quality website linked below under "Resources". Our goals are to understand our aquatic systems, monitor their health, and pursue restoration efforts when needed.

This program is made possible by our staff, advisory board, college interns, dedicated community volunteers, and support from local conservation organizations. If you have an interest in volunteering with us, check out our website below!

Note: Water Quality Samplers/Testers and Site Guide volunteer positions are 18+ age restricted.

**NBS Water Quality Website:** <https://normanbirdsanctuary.org/about/water-quality-monitoring-program/>
